// D1 Save Forge service worker — GENERATED by the d1-offline plugin in
// vite.config.ts (P-D7); do not edit. Precache list + version are stamped
// per build. Paths are SCOPE-relative so the same sw.js works at a domain
// root and under the GH Pages project subpath (item 25).
// Fetch policy (P-D7 code-cache contract): hashed assets are cache-first
// (immutable names); the stable-named shell + core payloads are NETWORK-
// first online — the HTTP-cache revalidation + V8 wasm code-cache path
// (P-D4) stays exactly as without a SW — with the precache copy as the
// offline fallback, refreshed in place on every successful network fetch.
// A non-ok network response (origin 5xx, bad deploy) falls back to the
// precache copy like a network failure would (review S4 2026-09-03).
// Update safety (review W3 2026-09-03, docs/research/
// 2026-09-03-sw-update-strategy/): activate RETAINS the newest previous
// d1sf-* generation (caches.keys() is creation-ordered — spec ordered
// map) and the fetch handler serves old-tab requests for paths that left
// the deploy from that retained cache: the origin drops old hashed files
// at deploy (force-pushed history), so without this a long-lived tab's
// lazy chunk 404s and its picker dead-ends.
const VERSION='bdb1876ed394';
const CACHE='d1sf-'+VERSION;
const SCOPE=self.registration.scope;
const REL=["assets/CatalogPicker-C1jLxxWo.js","assets/index-BJzhedPH.css","assets/index-lDsTgE0c.js","core/d1_core.data","core/d1_core.js","core/d1_core.wasm","icon-d1.svg","index.html","manifest.webmanifest"];
const P=REL.map(p=>new URL(p,SCOPE).pathname);
const NET=["core/d1_core.data","core/d1_core.js","core/d1_core.wasm","index.html"].map(p=>new URL(p,SCOPE).pathname);
const SET=new Set(P);
const NETSET=new Set(NET);
self.addEventListener('install',e=>{
  e.waitUntil(caches.open(CACHE).then(c=>c.addAll(P)).then(()=>self.skipWaiting()));
});
self.addEventListener('activate',e=>{
  e.waitUntil(caches.keys().then(ks=>{
    // Keep the newest PREVIOUS d1sf-* generation alive for old tabs (W3);
    // only generations older than that die here.
    const old=ks.filter(k=>k.startsWith('d1sf-')&&k!==CACHE);
    const keep=old[old.length-1];
    return Promise.all(old.filter(k=>k!==keep).map(k=>caches.delete(k)));
  }).then(()=>self.clients.claim()));
});
self.addEventListener('fetch',e=>{
  if(e.request.method!=='GET')return;
  const u=new URL(e.request.url);
  if(u.origin!==self.location.origin)return;
  let p=u.pathname;
  if(e.request.mode==='navigate'&&p.endsWith('/'))p+='index.html';
  const key=new URL(p,SCOPE);
  if(SET.has(p)&&NETSET.has(p)){
    e.respondWith(fetch(e.request).then(r=>{
      // Clone BEFORE returning r: respondWith starts consuming r's body the
      // moment this resolves, and a clone taken after an async gap throws
      // "body already used" (blind-review W1 2026-09-02).
      if(!r.ok)throw 0;
      const cp=r.clone();
      caches.open(CACHE).then(c=>c.put(key,cp)).catch(()=>{});
      return r;
      // .catch (NOT a second then-arg — that only sees the fetch rejection,
      // polish 2026-09-03): network failure AND non-ok both fall back to the
      // precache copy; a missing entry degrades to a network error response
      // instead of a TypeError out of respondWith.
    }).catch(()=>caches.open(CACHE).then(c=>c.match(key)).then(r=>r||Response.error())));
  }else{
    // Paths of THIS deploy read the CURRENT cache first — a global
    // caches.match is oldest-first, so stable names (manifest, icon) would
    // serve one deploy stale from the retained generation. Paths that left
    // the deploy (an old tab's hashed chunk) fall back to the retained
    // generation, then the origin (which 404s them).
    const hit=SET.has(p)?caches.open(CACHE).then(c=>c.match(key)):caches.match(key);
    e.respondWith(hit.then(r=>r||fetch(e.request)));
  }
});
