var createD1Core=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var Module=moduleArg;var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer";Module.expectedDataFileDownloads||(Module.expectedDataFileDownloads=0);Module.expectedDataFileDownloads++;
(()=>{var a=typeof ENVIRONMENT_IS_WASM_WORKER!="undefined"&&ENVIRONMENT_IS_WASM_WORKER;if(!(typeof ENVIRONMENT_IS_PTHREAD!="undefined"&&ENVIRONMENT_IS_PTHREAD||a)){var b=globalThis.process&&globalThis.process.versions&&globalThis.process.versions.node&&globalThis.process.type!="renderer";(async function(c){async function d(f,l){if(b){var n=require("fs").readFileSync(f);return(new Uint8Array(n)).buffer}Module.dataFileDownloads||(Module.dataFileDownloads={});try{var r=await fetch(f)}catch(y){throw Error(`Network Error: ${f}`,
{e:y});}if(!r.ok)throw Error(`${r.status}: ${r.url}`);n=[];l=Number(r.headers.get("Content-Length")||l);var t=0;Module.setStatus&&Module.setStatus("Downloading data...");for(r=r.body.getReader();;){var u;({done:u,value:x}=await r.read());if(u)break;n.push(x);t+=x.length;Module.dataFileDownloads[f]={loaded:t,total:l};var x=u=0;for(var w of Object.values(Module.dataFileDownloads))u+=w.loaded,x+=w.total;Module.setStatus&&Module.setStatus(`Downloading data... (${u}/${x})`)}f=new Uint8Array(n.map(y=>y.length).reduce((y,
F)=>y+F,0));w=0;for(let y of n)f.set(y,w),w+=y.length;return f.buffer}async function e(f){f.FS_createPath("/","assets",!0,!0);f.FS_createPath("/assets","fonts",!0,!0);f.FS_createPath("/assets","txtdata",!0,!0);f.FS_createPath("/assets/txtdata","classes",!0,!0);f.FS_createPath("/assets/txtdata/classes","barbarian",!0,!0);f.FS_createPath("/assets/txtdata/classes","bard",!0,!0);f.FS_createPath("/assets/txtdata/classes","monk",!0,!0);f.FS_createPath("/assets/txtdata/classes","rogue",!0,!0);f.FS_createPath("/assets/txtdata/classes",
"sorcerer",!0,!0);f.FS_createPath("/assets/txtdata/classes","warrior",!0,!0);f.FS_createPath("/assets/txtdata","items",!0,!0);f.FS_createPath("/assets/txtdata","monsters",!0,!0);f.FS_createPath("/assets/txtdata","spells",!0,!0);f.FS_createPath("/","mods",!0,!0);f.FS_createPath("/mods","hf",!0,!0);f.FS_createPath("/mods/hf","txtdata",!0,!0);f.FS_createPath("/mods/hf/txtdata","classes",!0,!0);f.FS_createPath("/mods/hf/txtdata/classes","sorcerer",!0,!0);f.FS_createPath("/mods/hf/txtdata","items",!0,
!0);f.FS_createPath("/mods/hf/txtdata","monsters",!0,!0);f.FS_createPath("/mods/hf/txtdata","spells",!0,!0);f.addRunDependency("datafile_/Users/samuelecioni/Dropbox/d1/editor/packages/engine/dist/d1_core.data");f.preloadResults||(f.preloadResults={});f.preloadResults["/Users/samuelecioni/Dropbox/d1/editor/packages/engine/dist/d1_core.data"]={lb:!1};q||=await m;await async function(l){if(!l)throw Error("Loading data file failed.");if(l.constructor.name!==ArrayBuffer.name)throw Error("bad input to processPackageData "+
l.constructor.name);l=new Uint8Array(l);for(var n of c.files)f.FS_createDataFile(n.filename,null,l.subarray(n.start,n.end),!0,!0,!0);f.removeRunDependency("datafile_/Users/samuelecioni/Dropbox/d1/editor/packages/engine/dist/d1_core.data")}(q)}typeof window==="object"?window.encodeURIComponent(window.location.pathname.substring(0,window.location.pathname.lastIndexOf("/"))+"/"):typeof process==="undefined"&&typeof location!=="undefined"&&encodeURIComponent(location.pathname.substring(0,location.pathname.lastIndexOf("/"))+
"/");var g=Module.locateFile?Module.locateFile("d1_core.data",""):"d1_core.data",h=c.remote_package_size,m,q=Module.getPreloadedPackage&&Module.getPreloadedPackage(g,h);q||(m=d(g,h));Module.FS_createPath?e(Module):(Module.preRun||(Module.preRun=[]),Module.preRun.push(e))})({files:[{filename:"/assets/fonts/12-00.clx",start:0,end:17383},{filename:"/assets/txtdata/Experience.tsv",start:17383,end:17950},{filename:"/assets/txtdata/classes/barbarian/animations.tsv",start:17950,end:18489},{filename:"/assets/txtdata/classes/barbarian/attributes.tsv",
start:18489,end:18816},{filename:"/assets/txtdata/classes/barbarian/sounds.tsv",start:18816,end:21764},{filename:"/assets/txtdata/classes/barbarian/sprites.tsv",start:21764,end:21930},{filename:"/assets/txtdata/classes/barbarian/starting_loadout.tsv",start:21930,end:22083},{filename:"/assets/txtdata/classes/bard/animations.tsv",start:22083,end:22628},{filename:"/assets/txtdata/classes/bard/attributes.tsv",start:22628,end:22932},{filename:"/assets/txtdata/classes/bard/sounds.tsv",start:22932,end:25673},
{filename:"/assets/txtdata/classes/bard/sprites.tsv",start:25673,end:25833},{filename:"/assets/txtdata/classes/bard/starting_loadout.tsv",start:25833,end:25992},{filename:"/assets/txtdata/classes/classdat.tsv",start:25992,end:26171},{filename:"/assets/txtdata/classes/monk/animations.tsv",start:26171,end:26713},{filename:"/assets/txtdata/classes/monk/attributes.tsv",start:26713,end:27005},{filename:"/assets/txtdata/classes/monk/sounds.tsv",start:27005,end:29530},{filename:"/assets/txtdata/classes/monk/sprites.tsv",
start:29530,end:29694},{filename:"/assets/txtdata/classes/monk/starting_loadout.tsv",start:29694,end:29846},{filename:"/assets/txtdata/classes/rogue/animations.tsv",start:29846,end:30390},{filename:"/assets/txtdata/classes/rogue/attributes.tsv",start:30390,end:30690},{filename:"/assets/txtdata/classes/rogue/sounds.tsv",start:30690,end:33431},{filename:"/assets/txtdata/classes/rogue/sprites.tsv",start:33431,end:33592},{filename:"/assets/txtdata/classes/rogue/starting_loadout.tsv",start:33592,end:33743},
{filename:"/assets/txtdata/classes/sorcerer/animations.tsv",start:33743,end:34286},{filename:"/assets/txtdata/classes/sorcerer/attributes.tsv",start:34286,end:34571},{filename:"/assets/txtdata/classes/sorcerer/sounds.tsv",start:34571,end:37621},{filename:"/assets/txtdata/classes/sorcerer/sprites.tsv",start:37621,end:37791},{filename:"/assets/txtdata/classes/sorcerer/starting_loadout.tsv",start:37791,end:37959},{filename:"/assets/txtdata/classes/warrior/animations.tsv",start:37959,end:38499},{filename:"/assets/txtdata/classes/warrior/attributes.tsv",
start:38499,end:38800},{filename:"/assets/txtdata/classes/warrior/sounds.tsv",start:38800,end:41751},{filename:"/assets/txtdata/classes/warrior/sprites.tsv",start:41751,end:41915},{filename:"/assets/txtdata/classes/warrior/starting_loadout.tsv",start:41915,end:42076},{filename:"/assets/txtdata/items/item_prefixes.tsv",start:42076,end:47621},{filename:"/assets/txtdata/items/item_suffixes.tsv",start:47621,end:53884},{filename:"/assets/txtdata/items/itemdat.tsv",start:53884,end:71878},{filename:"/assets/txtdata/items/unique_itemdat.tsv",
start:71878,end:80898},{filename:"/assets/txtdata/monsters/monstdat.tsv",start:80898,end:108137},{filename:"/assets/txtdata/monsters/unique_monstdat.tsv",start:108137,end:118813},{filename:"/assets/txtdata/spells/spelldat.tsv",start:118813,end:121878},{filename:"/mods/hf/manifest.ini",start:121878,end:122145},{filename:"/mods/hf/txtdata/classes/classdat.tsv",start:122145,end:122324},{filename:"/mods/hf/txtdata/classes/sorcerer/starting_loadout.tsv",start:122324,end:122485},{filename:"/mods/hf/txtdata/items/item_prefixes.tsv",
start:122485,end:128276},{filename:"/mods/hf/txtdata/items/item_suffixes.tsv",start:128276,end:134828},{filename:"/mods/hf/txtdata/items/unique_itemdat.tsv",start:134828,end:145766},{filename:"/mods/hf/txtdata/monsters/monstdat.tsv",start:145766,end:179553},{filename:"/mods/hf/txtdata/spells/spelldat.tsv",start:179553,end:183892}],remote_package_size:183892})}})();var da="./this.program",ea=(a,b)=>{throw b;};typeof __filename!="undefined"&&(_scriptName=__filename);var fa="",ha,ia;
if(ca){var fs=require("node:fs");fa=__dirname+"/";ia=a=>{a=ja(a)?new URL(a):a;return fs.readFileSync(a)};ha=async a=>{a=ja(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.length>1&&(da=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);ea=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{fa=(new URL(".",_scriptName)).href}catch{}ha=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}
var ka=console.log.bind(console),k=console.error.bind(console),la=!1,ja=a=>a.startsWith("file://");function ma(){if(!p?.buffer?.resizable){var a=na.buffer;p=new Int8Array(a);v=new Int16Array(a);Module.HEAPU8=z=new Uint8Array(a);A=new Int32Array(a);B=new Uint32Array(a);oa=new Float32Array(a);pa=new Float64Array(a);C=new BigInt64Array(a)}}function qa(){var a=Module.preRun;a&&(typeof a=="function"&&(a=[a]),ra.push(...a));for(a=ra;a.length>0;)a.shift()(Module)}
function sa(){var a=Module.postRun;a&&(typeof a=="function"&&(a=[a]),ta.push(...a));for(a=ta;a.length>0;)a.shift()(Module)}function D(a){Module.onAbort?.(a);a=`Aborted(${a})`;k(a);la=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;async function va(a){try{var b=await ha(a);return new Uint8Array(b)}catch{}if(ia)a=ia(a);else throw"both async and sync fetching of the wasm failed";return a}
async function wa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),D(d)}}async function xa(a){var b=ua;if(!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return wa(b,a)}
class ya{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var p,ta=[],ra=[],za=!0,Aa=(a,b)=>{for(var c=0,d=a.length-1;d>=0;d--){var e=a[d];e==="."?a.splice(d,1):e===".."?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},G=a=>{var b=a.charAt(0)==="/",c=a.slice(-1)==="/";(a=Aa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ba=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},
H=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Ca=()=>{if(ca){var a=require("node:crypto");return b=>(a.randomFillSync(b),0)}return b=>(crypto.getRandomValues(b),0)},Da=a=>(Da=Ca())(a),Ea=(...a)=>{for(var b="",c=!1,d=a.length-1;d>=-1&&!c;d--){c=d>=0?a[d]:"/";if(typeof c!="string")throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c=c.charAt(0)==="/"}b=Aa(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Fa=(a,b)=>{function c(h){for(var m=0;m<h.length&&
h[m]==="";m++);for(var q=h.length-1;q>=0&&h[q]==="";q--);return m>q?[]:h.slice(m,q-m+1)}a=Ea(a).slice(1);b=Ea(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,g=0;g<d;g++)if(a[g]!==b[g]){e=g;break}d=[];for(g=e;g<a.length;g++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},Ga=new TextDecoder,Ha=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},Ia=a=>{var b=Ha(a,0);return Ga.decode(a.buffer?a.subarray(0,b):new Uint8Array(a.slice(0,b)))},
Ja=[],Ka=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},La=(a,b,c,d)=>{if(!(d>0))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.codePointAt(g);if(h<=127){if(c>=d)break;b[c++]=h}else if(h<=2047){if(c+1>=d)break;b[c++]=192|h>>6;b[c++]=128|h&63}else if(h<=65535){if(c+2>=d)break;b[c++]=224|h>>12;b[c++]=128|h>>6&63;b[c++]=128|h&63}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63;b[c++]=128|h>>6&63;b[c++]=
128|h&63;g++}}b[c]=0;return c-e},Ma=a=>{var b=Array(Ka(a)+1);a=La(a,b,0,b.length);b.length=a;return b},Na=[];function Oa(a,b){Na[a]={input:[],output:[],ua:b};Pa(a,Qa)}
var Qa={open(a){var b=Na[a.node.rdev];if(!b)throw new I(43);a.tty=b;a.seekable=!1},close(a){a.tty.ua.fsync(a.tty)},fsync(a){a.tty.ua.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.ua.Ja)throw new I(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.ua.Ja(a.tty)}catch(m){throw new I(29);}if(h===void 0&&!e)throw new I(6);if(h===null||h===void 0)break;e++;b[c+g]=h}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.ua.Ha)throw new I(60);try{for(var e=0;e<d;e++)a.tty.ua.Ha(a.tty,b[c+e])}catch(g){throw new I(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},Ra={Ja(){a:{if(!Ja.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}c>0&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),a!==null&&(a+="\n"));if(!a){a=null;break a}Ja=Ma(a)}a=Ja.shift()}return a},Ha(a,b){b===null||b===10?(ka(Ia(a.output)),a.output=[]):b!=0&&a.output.push(b)},fsync(a){a.output?.length>
0&&(ka(Ia(a.output)),a.output=[])},Ta(){return{gb:25856,ib:5,fb:191,hb:35387,eb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Ua(){return 0},Va(){return[24,80]}},Sa={Ha(a,b){b===null||b===10?(k(Ia(a.output)),a.output=[]):b!=0&&a.output.push(b)},fsync(a){a.output?.length>0&&(k(Ia(a.output)),a.output=[])}},J={sa:null,qa(){return J.createNode(null,"/",16895,0)},createNode(a,b,c,d){if((c&61440)===24576||(c&61440)===4096)throw new I(63);J.sa||(J.sa={dir:{node:{ta:J.la.ta,
va:J.la.va,lookup:J.la.lookup,Ba:J.la.Ba,rename:J.la.rename,unlink:J.la.unlink,rmdir:J.la.rmdir,readdir:J.la.readdir,symlink:J.la.symlink},stream:{ra:J.ma.ra}},file:{node:{ta:J.la.ta,va:J.la.va},stream:{ra:J.ma.ra,read:J.ma.read,write:J.ma.write,Fa:J.ma.Fa,Ma:J.ma.Ma}},link:{node:{ta:J.la.ta,va:J.la.va,readlink:J.la.readlink},stream:{}},Ia:{node:{ta:J.la.ta,va:J.la.va},stream:Ta}});c=Ua(a,b,c,d);K(c.mode)?(c.la=J.sa.dir.node,c.ma=J.sa.dir.stream,c.na={}):(c.mode&61440)===32768?(c.la=J.sa.file.node,
c.ma=J.sa.file.stream,c.pa=0,c.na=J.Ra??(J.Ra=new Uint8Array(0))):(c.mode&61440)===40960?(c.la=J.sa.link.node,c.ma=J.sa.link.stream):(c.mode&61440)===8192&&(c.la=J.sa.Ia.node,c.ma=J.sa.Ia.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.na[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},la:{ta(a){var b={};b.dev=(a.mode&61440)===8192?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;K(a.mode)?b.size=4096:(a.mode&61440)===32768?b.size=a.pa:(a.mode&61440)===40960?b.size=a.link.length:
b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},va(a,b){for(var c of["mode","atime","mtime","ctime"])b[c]!=null&&(a[c]=b[c]);b.size!==void 0&&(b=b.size,a.pa!=b&&(c=a.na,a.na=new Uint8Array(b),a.na.set(c.subarray(0,Math.min(b,a.pa))),a.pa=b))},lookup(){J.Ca||(J.Ca=new I(44),J.Ca.stack="<generic error, no stack>");throw J.Ca;},Ba(a,b,c,d){return J.createNode(a,b,c,d)},rename(a,b,c){try{var d=L(b,c)}catch(g){}if(d){if(K(a.mode))for(var e in d.na)throw new I(55);
Va(d)}delete a.parent.na[a.name];b.na[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.na[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=L(a,b),d;for(d in c.na)throw new I(55);delete a.na[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.na)]},symlink(a,b,c){a=J.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if((a.mode&61440)!==40960)throw new I(28);return a.link}},ma:{read(a,b,c,d,e){if(e>=a.node.pa)return 0;d=Math.min(a.node.pa-
e,d);b.set(a.node.na.subarray(e,e+d),c);return d},write(a,b,c,d,e,g){b.buffer===p.buffer&&(g=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(g)a.na=b.subarray(c,c+d),a.pa=d;else if(a.pa||e){g=e+d;var h=a.na.length;h>=g||(g=Math.max(g,h*(h<1048576?2:1.125)>>>0),h&&(g=Math.max(g,256)),h=a.na.subarray(0,a.pa),a.na=new Uint8Array(g),a.na.set(h));a.na.set(b.subarray(c,c+d),e);a.pa=Math.max(a.pa,e+d)}else a.na=b.slice(c,c+d),a.pa=d;return d},ra(a,b,c){c===1?b+=a.position:c===2&&(a.node.mode&61440)===
32768&&(b+=a.node.pa);if(b<0)throw new I(28);return b},Fa(a,b,c,d,e){if((a.node.mode&61440)!==32768)throw new I(43);a=a.node.na;if(e&2||a.buffer!==p.buffer){d=!0;D();e=void 0;if(!e)throw new I(48);if(a){if(c>0||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);p.set(a,e)}}else d=!1,e=a.byteOffset;return{nb:e,cb:d}},Ma(a,b,c,d){J.ma.write(a,b,0,d,c,!1);return 0}}},Wa=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Xa=async a=>{a=await ha(a);return new Uint8Array(a)},
Ya=null,Za=async()=>Ya,M=0,$a=null,ab=()=>{M--;Module.monitorRunDependencies?.(M);M||$a()},bb=()=>{M||(Ya=new Promise(a=>$a=a));M++;Module.monitorRunDependencies?.(M)},cb=[],db=async(a,b)=>{typeof Browser!="undefined"&&Browser.init();for(var c of cb)if(c.canHandle(b))return c.handle(a,b);return a},eb=null,fb={},N=[],gb=1,O=null,hb=!1,ib=!0,I=class{name="ErrnoError";constructor(a){this.oa=a}},jb=class{shared={};node=null;get flags(){return this.shared.flags}set flags(a){this.shared.flags=a}get position(){return this.shared.position}set position(a){this.shared.position=
a}},kb=class{la={};ma={};wa=null;listeners=null;ya=0;constructor(a,b,c,d){a||=this;this.parent=a;this.qa=a.qa;this.id=gb++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return(this.mode&365)===365}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return(this.mode&146)===146}set write(a){a?this.mode|=146:this.mode&=-147}get Xa(){return K(this.mode)}get Wa(){return(this.mode&61440)===8192}$a(){if(this.listeners){var a;for(b of this.listeners)b.exclusive?
(a||=[]).push(b):b.Qa(32);if(a){var b=(this.ya||0)%a.length;this.ya=b+1;a[b].Qa(32)}}}};
function P(a,b={}){if(!a)throw new I(44);b.Da??(b.Da=!0);a.charAt(0)==="/"||(a="//"+a);var c=0;a:for(;c<40;c++){a=a.split("/").filter(m=>!!m);for(var d=eb,e="/",g=0;g<a.length;g++){var h=g===a.length-1;if(h&&b.parent)break;if(a[g]!==".")if(a[g]==="..")if(e=Ba(e),d===d.parent){a=e+"/"+a.slice(g+1).join("/");c--;continue a}else d=d.parent;else{e=G(e+"/"+a[g]);try{d=L(d,a[g])}catch(m){if(m?.oa===44&&h&&b.Za)return{path:e};throw m;}!d.wa||h&&!b.Da||(d=d.wa.root);if((d.mode&61440)===40960&&(!h||b.za)){if(!d.la.readlink)throw new I(52);
d=d.la.readlink(d);d.charAt(0)==="/"||(d=Ba(e)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:e,node:d}}throw new I(32);}function Q(a){for(var b;;){if(a===a.parent)return a=a.qa.La,b?a[a.length-1]!=="/"?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function lb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%O.length}function mb(a){var b=lb(a.parent.id,a.name);a.Aa=O[b];O[b]=a}
function Va(a){var b=lb(a.parent.id,a.name);if(O[b]===a)O[b]=a.Aa;else for(b=O[b];b;){if(b.Aa===a){b.Aa=a.Aa;break}b=b.Aa}}function L(a,b){var c=K(a.mode)?(c=R(a,"x"))?c:a.la.lookup?0:2:54;if(c)throw new I(c);for(c=O[lb(a.id,b)];c;c=c.Aa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.la.lookup(a,b)}function Ua(a,b,c,d){a=new kb(a,b,c,d);mb(a);return a}function K(a){return(a&61440)===16384}
function R(a,b){return ib?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function nb(a,b){if(!K(a.mode))return 54;try{return L(a,b),20}catch(c){}return R(a,"wx")}function ob(a,b,c){try{var d=L(a,b)}catch(e){return e.oa}if(a=R(a,"wx"))return a;if(c){if(!K(d.mode))return 54;if(d===d.parent||Q(d)==="/")return 10}else if(K(d.mode))return 31;return 0}function pb(a,b){if(!a)throw new I(b);return a}function S(a){a=N[a];if(!a)throw new I(8);return a}
function qb(a,b=-1){a=Object.assign(new jb,a);if(b==-1)a:{for(b=0;b<=4096;b++)if(!N[b])break a;throw new I(33);}a.fd=b;return N[b]=a}function rb(a,b=-1){a=qb(a,b);a.ma?.kb?.(a);return a}function sb(a,b){var c=void 0,d=c?null:a;c??=a.la.va;pb(c,63);try{c(d,b)}catch(e){if(e instanceof RangeError)throw new I(22);throw e;}}var Ta={open(a){a.ma=fb[a.node.rdev].ma;a.ma.open?.(a)},ra(){throw new I(70);}};function Pa(a,b){fb[a]={ma:b}}
function tb(a,b){var c=b==="/";if(c&&eb)throw new I(10);if(!c&&b){var d=P(b,{Da:!1});b=d.path;d=d.node;if(d.wa)throw new I(10);if(!K(d.mode))throw new I(54);}b={type:a,mb:{},La:b,Ya:[]};a=a.qa(b);a.qa=b;b.root=a;c?eb=a:d&&(d.wa=b,d.qa&&d.qa.Ya.push(b))}function ub(a,b,c){var d=P(a,{parent:!0}).node;a=H(a);if(!a)throw new I(28);if(a==="."||a==="..")throw new I(20);var e=nb(d,a);if(e)throw new I(e);if(!d.la.Ba)throw new I(63);return d.la.Ba(d,a,b,c)}
function vb(a,b=438){return ub(a,b&4095|32768,0)}function T(a,b=511){return ub(a,b&1023|16384,0)}function wb(a,b,c){typeof c=="undefined"&&(c=b,b=438);return ub(a,b|8192,c)}function xb(a,b){if(!Ea(a))throw new I(44);var c=P(b,{parent:!0}).node;if(!c)throw new I(44);b=H(b);var d=nb(c,b);if(d)throw new I(d);if(!c.la.symlink)throw new I(63);c.la.symlink(c,b,a)}
function yb(a){var b=P(a,{parent:!0}).node;a=H(a);var c=L(b,a),d=ob(b,a,!0);if(d)throw new I(d);if(!b.la.rmdir)throw new I(63);if(c.wa)throw new I(10);b.la.rmdir(b,a);Va(c)}function zb(a){var b=P(a,{parent:!0}).node;if(!b)throw new I(44);a=H(a);var c=L(b,a),d=ob(b,a,!1);if(d)throw new I(d);if(!b.la.unlink)throw new I(63);if(c.wa)throw new I(10);b.la.unlink(b,a);Va(c)}function Ab(a,b){a=typeof a=="string"?P(a,{za:!0}).node:a;sb(a,{mode:b&4095|a.mode&-4096,ctime:Date.now(),jb:void 0})}
function Bb(a,b,c=438){if(a==="")throw new I(44);if(typeof b=="string"){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if(typeof d=="undefined")throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if(typeof a=="object")d=a;else{var e=a.endsWith("/");var g=P(a,{za:!(b&131072),Za:!0});d=g.node;a=g.path}g=!1;if(b&64)if(d){if(b&128)throw new I(20);}else{if(e)throw new I(31);d=ub(a,c|511,0);g=!0}if(!d)throw new I(44);(d.mode&61440)===8192&&(b&=-513);if(b&65536&&!K(d.mode))throw new I(54);
if(!g&&(d?(d.mode&61440)===40960?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=K(d.mode)&&(e!=="r"||b&576)?31:R(d,e)):e=44,e))throw new I(e);if(b&512&&!g){e=d;e=typeof e=="string"?P(e,{za:!0}).node:e;if(K(e.mode))throw new I(31);if((e.mode&61440)!==32768)throw new I(28);if(a=R(e,"w"))throw new I(a);sb(e,{size:0,timestamp:Date.now()})}b=qb({node:d,path:Q(d),flags:b&-131713,seekable:!0,position:0,ma:d.ma,bb:[],error:!1});b.ma.open&&b.ma.open(b);g&&Ab(d,c&511);return b}
function Cb(a){if(a.fd===null)throw new I(8);a.xa&&(a.xa=null);a.node?.$a();try{a.ma.close&&a.ma.close(a)}catch(b){throw b;}finally{N[a.fd]=null}a.fd=null}function Db(a,b,c){if(a.fd===null)throw new I(8);if(!a.seekable||!a.ma.ra)throw new I(70);if(c!=0&&c!=1&&c!=2)throw new I(28);a.position=a.ma.ra(a,b,c);a.bb=[];return a.position}
function Eb(a,b,c,d,e,g){if(d<0||e<0)throw new I(28);if(a.fd===null)throw new I(8);if((a.flags&2097155)===0)throw new I(8);if(K(a.node.mode))throw new I(31);if(!a.ma.write)throw new I(28);a.seekable&&a.flags&1024&&Db(a,0,2);var h=typeof e!="undefined";if(!h)e=a.position;else if(!a.seekable)throw new I(70);b=a.ma.write(a,b,c,d,e,g);h||(a.position+=b);return b}
function Fb(){var a,b,c;hb=!0;a??=Module.stdin;b??=Module.stdout;c??=Module.stderr;a?U("/dev","stdin",a):xb("/dev/tty","/dev/stdin");b?U("/dev","stdout",null,b):xb("/dev/tty","/dev/stdout");c?U("/dev","stderr",null,c):xb("/dev/tty1","/dev/stderr");Bb("/dev/stdin",0);Bb("/dev/stdout",1);Bb("/dev/stderr",1)}function Gb(a,b){a=typeof a=="string"?a:Q(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=G(a+"/"+c);try{T(d)}catch(e){if(e.oa!=20)throw e;}a=d}}return d}
function Hb(a,b,c,d){a=G((typeof a=="string"?a:Q(a))+"/"+b);return vb(a,Wa(c,d))}function Ib(a,b,c,d,e,g){var h=b;a&&(a=typeof a=="string"?a:Q(a),h=b?G(a+"/"+b):a);a=Wa(d,e);h=vb(h,a);c&&(typeof c=="string"&&(c=Ma(c)),c.subarray||(c=new Uint8Array(c)),Ab(h,a|146),b=Bb(h,577),Eb(b,c,0,c.length,0,g),Cb(b),Ab(h,a))}
function U(a,b,c,d){a=G((typeof a=="string"?a:Q(a))+"/"+b);b=Wa(!!c,!!d);U.Ka??(U.Ka=64);var e=U.Ka++<<8|0;Pa(e,{open(g){g.seekable=!1},close(){d?.buffer?.length&&d(10)},read(g,h,m,q){for(var f=0,l=0;l<q;l++){try{var n=c()}catch(r){throw new I(29);}if(n===void 0&&!f)throw new I(6);if(n===null||n===void 0)break;f++;h[m+l]=n}f&&(g.node.atime=Date.now());return f},write(g,h,m,q){for(var f=0;f<q;f++)try{d(h[m+f])}catch(l){throw new I(29);}q&&(g.node.mtime=g.node.ctime=Date.now());return f}});return wb(a,
b,e)}function Jb(a){if(!(a.Wa||a.Xa||a.link||a.na))if(globalThis.XMLHttpRequest)D("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.na=ia(a.url)}catch(b){throw new I(29);}}
function Kb(a,b,c,d,e){class g{Ga=!1;ya=[];Ea=void 0;Oa=0;Na=0;get(f){if(!(f>this.length-1||f<0)){var l=f%this.chunkSize;return this.Ea(f/this.chunkSize|0)[l]}}ab(f){this.Ea=f}Pa(){var f=new XMLHttpRequest;f.open("HEAD",c,!1);f.send(null);f.status>=200&&f.status<300||f.status===304||D(`Couldn't load ${c}. Status: ${f.status}`);var l=Number(f.getResponseHeader("Content-length")),n,r=(n=f.getResponseHeader("Accept-Ranges"))&&n==="bytes";f=(n=f.getResponseHeader("Content-Encoding"))&&n==="gzip";var t=
1048576;r||(t=l);var u=this;u.ab(x=>{var w=x*t,y=(x+1)*t-1;y=Math.min(y,l-1);if(typeof u.ya[x]=="undefined"){var F=u.ya;w>y&&D(`invalid range (${w}, ${y}) or no bytes requested!`);y>l-1&&D(`only ${l} bytes available! programmer error!`);var E=new XMLHttpRequest;E.open("GET",c,!1);l!==t&&E.setRequestHeader("Range",`bytes=${w}-${y}`);E.responseType="arraybuffer";E.overrideMimeType&&E.overrideMimeType("text/plain; charset=x-user-defined");E.send(null);E.status>=200&&E.status<300||E.status===304||D(`Couldn't load ${c}. Status: ${E.status}`);
w=E.response!==void 0?new Uint8Array(E.response||[]):Ma(E.responseText??"");F[x]=w}typeof u.ya[x]=="undefined"&&D("doXHR failed!");return u.ya[x]});if(f||!l)t=l=1,t=l=this.Ea(0).length,ka("LazyFiles on gzip forces download of the whole file when length is accessed");this.Oa=l;this.Na=t;this.Ga=!0}get length(){this.Ga||this.Pa();return this.Oa}get chunkSize(){this.Ga||this.Pa();return this.Na}}if(globalThis.XMLHttpRequest){ba||D("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var h=new g;var m=void 0}else m=c,h=void 0;var q=Hb(a,b,d,e);h?q.na=h:m&&(q.na=null,q.url=m);Object.defineProperties(q,{pa:{get:function(){return this.na.length}}});a={};for(let [f,l]of Object.entries(q.ma))a[f]=(...n)=>{Jb(q);return l(...n)};a.read=(f,l,n,r,t)=>{Jb(q);f=f.node.na;if(t>=f.length)l=0;else{r=Math.min(f.length-t,r);if(f.slice)for(var u=0;u<r;u++)l[n+u]=f[t+u];else for(u=0;u<r;u++)l[n+u]=f.get(t+u);l=r}return l};a.Fa=()=>{Jb(q);D();throw new I(48);};q.ma=a;return q}
var V={},z,W=(a,b,c)=>a?Ga.decode(z.subarray(a,Ha(z,a,b,c))):"",A,B,C;function X(a,b){if(b.charAt(0)==="/")return b;a=a===-100?"/":S(a).path;if(b.length==0)throw new I(44);return a+"/"+b}
var Lb=void 0,Y=()=>{var a=A[+Lb>>2];Lb+=4;return a},v,Mb={},Ob=()=>{if(!Nb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:da},b;for(b in Mb)Mb[b]===void 0?delete a[b]:a[b]=Mb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Nb=c}return Nb},Nb,Pb=a=>{za||(Module.onExit?.(a),la=!0);ea(a,new ya(a))},Tb=(a,b,c,d)=>{var e={string:f=>{var l=0;if(f!==null&&f!==void 0&&f!==0){l=Ka(f)+1;var n=Qb(l);La(f,
z,n,l);l=n}return l},array:f=>{var l=Qb(f.length);p.set(f,l);return l}};a=Module["_"+a];var g=[],h=0;if(d)for(var m=0;m<d.length;m++){var q=e[c[m]];q?(h||=Rb(),g[m]=q(d[m])):g[m]=d[m]}c=a(...g);return c=function(f){h&&Sb(h);return b==="string"?W(f):b==="boolean"?!!f:f}(c)},oa,pa;O=Array(4096);tb(J,"/");T("/tmp");T("/home");T("/home/web_user");
(function(){T("/dev");Pa(259,{read:()=>0,write:(d,e,g,h)=>h,ra:()=>0});wb("/dev/null",259);Oa(1280,Ra);Oa(1536,Sa);wb("/dev/tty",1280);wb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{b||(Da(a),b=a.byteLength);return a[--b]};U("/dev","random",c);U("/dev","urandom",c);T("/dev/shm");T("/dev/shm/tmp")})();
(function(){T("/proc");var a=T("/proc/self");T("/proc/self/fd");tb({qa(){var b=Ua(a,"fd",16895,73);b.ma={ra:J.ma.ra};b.la={lookup(c,d){c=+d;var e=S(c);c={parent:null,qa:{La:"fake"},la:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(N.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();Module.noExitRuntime&&(za=Module.noExitRuntime);Module.print&&(ka=Module.print);Module.printErr&&(k=Module.printErr);Module.thisProgram&&(da=Module.thisProgram);
var Z=Module.preInit;if(Z)for(typeof Z=="function"&&(Module.preInit=Z=[Z]);Z.length>0;)Z.shift()();Module.addRunDependency=bb;Module.removeRunDependency=ab;Module.ccall=Tb;Module.cwrap=(a,b,c,d)=>{var e=!c||c.every(g=>g==="number"||g==="boolean");return b!=="string"&&e&&!d?Module["_"+a]:(...g)=>Tb(a,b,c,g,d)};
Module.setValue=function(a,b,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":p[a]=b;break;case "i8":p[a]=b;break;case "i16":v[a>>1]=b;break;case "i32":A[a>>2]=b;break;case "i64":C[a>>3]=BigInt(b);break;case "float":oa[a>>2]=b;break;case "double":pa[a>>3]=b;break;case "*":B[a>>2]=b;break;default:D(`invalid type for setValue: ${c}`)}};
Module.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return p[a];case "i8":return p[a];case "i16":return v[a>>1];case "i32":return A[a>>2];case "i64":return C[a>>3];case "float":return oa[a>>2];case "double":return pa[a>>3];case "*":return B[a>>2];default:D(`invalid type for getValue: ${b}`)}};Module.UTF8ToString=W;
Module.FS_preloadFile=async(a,b,c,d,e,g,h,m)=>{var q=b?Ea(G(a+"/"+b)):a,f=`cp ${q}`;bb(f);try{var l=c;typeof c=="string"&&(l=await Xa(c));l=await db(l,q);m?.();g||Ib(a,b,l,d,e,h)}finally{ab(f)}};Module.FS_unlink=(...a)=>zb(...a);Module.FS_createPath=(...a)=>Gb(...a);Module.FS_createDevice=(...a)=>U(...a);Module.FS_createDataFile=(...a)=>Ib(...a);Module.FS_createLazyFile=(...a)=>Kb(...a);
var Ub,Sb,Qb,Rb,na,Vb={h:function(a,b,c){try{b=W(b);b=X(a,b);if(c&-8)return-28;var d=P(b,{za:!0}).node;if(!d)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&R(d,a)?-2:0}catch(e){if(typeof V=="undefined"||e.name!=="ErrnoError")throw e;return-e.oa}},c:function(a,b,c){Lb=c;try{var d=S(a);switch(b){case 0:var e=Y();if(e<0)break;for(;N[e];)e++;return rb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Y(),d.flags=d.flags&-289793|e&289792,0;case 12:return e=Y(),v[e+
0>>1]=2,0;case 13:case 14:return 0}return-28}catch(g){if(typeof V=="undefined"||g.name!=="ErrnoError")throw g;return-g.oa}},n:function(a,b,c){try{var d=S(a);if(!d.xa){var e=P(d.path,{za:!0}).node;var g=pb(e.la.readdir,54)(e);d.xa=g}a=0;var h=Db(d,0,1),m=Math.floor(h/280),q=Math.min(d.xa.length,m+Math.floor(c/280));for(c=m;c<q;c++){var f=d.xa[c];if(f==="."){var l=d.node.id;var n=4}else if(f==="..")l=P(d.path,{parent:!0}).node.id,n=4;else{try{var r=L(d.node,f)}catch(t){if(t?.oa===28)continue;throw t;
}l=r.id;n=(r.mode&61440)===8192?2:K(r.mode)?4:(r.mode&61440)===40960?10:8}C[b+a>>3]=BigInt(l);C[b+a+8>>3]=BigInt((c+1)*280);v[b+a+16>>1]=280;p[b+a+18]=n;La(f,z,b+a+19,256);a+=280}Db(d,c*280,0);return a}catch(t){if(typeof V=="undefined"||t.name!=="ErrnoError")throw t;return-t.oa}},k:function(a,b,c){Lb=c;try{var d=S(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.ua.Ta){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Y();A[e>>2]=
25856;A[e+4>>2]=5;A[e+8>>2]=191;A[e+12>>2]=35387;for(var g=0;g<32;g++)p[e+g+17]=a[g]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.ua.Ua)for(e=Y(),a=[],g=0;g<32;g++)a.push(p[e+g+17]);return 0;case 21519:if(!d.tty)return-59;e=Y();return A[e>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:e=Y();if(!d.ma.Sa)throw new I(59);return d.ma.Sa(d,b,e);case 21523:if(!d.tty)return-59;d.tty.ua.Va&&(g=[24,80],e=Y(),v[e>>
1]=g[0],v[e+2>>1]=g[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if(typeof V=="undefined"||h.name!=="ErrnoError")throw h;return-h.oa}},m:function(a,b,c){try{return b=W(b),b=X(a,b),T(b,c&-19),0}catch(d){if(typeof V=="undefined"||d.name!=="ErrnoError")throw d;return-d.oa}},d:function(a,b,c,d){Lb=d;try{b=W(b);b=X(a,b);var e=d?Y():0;c&64&&(e&=-19);return Bb(b,c,e).fd}catch(g){if(typeof V=="undefined"||g.name!=="ErrnoError")throw g;return-g.oa}},
q:function(a,b,c,d){try{b=W(b);d=W(d);b=X(a,b);d=X(c,d);a=b;var e=Ba(a),g=Ba(d),h=H(a),m=H(d);var q=P(a,{parent:!0});var f=q.node;q=P(d,{parent:!0});var l=q.node;if(!f||!l)throw new I(44);if(f.qa!==l.qa)throw new I(75);var n=L(f,h),r=Fa(a,g);if(r.charAt(0)!==".")throw new I(28);r=Fa(d,e);if(r.charAt(0)!==".")throw new I(55);try{var t=L(l,m)}catch(w){}if(n!==t){var u=K(n.mode),x=ob(f,h,u);if(x)throw new I(x);if(x=t?ob(l,m,u):nb(l,m))throw new I(x);if(!f.la.rename)throw new I(63);if(n.wa||t&&t.wa)throw new I(10);
if(l!==f&&(x=R(f,"w")))throw new I(x);Va(n);try{f.la.rename(n,l,m),n.parent=l}catch(w){throw w;}finally{mb(n)}}return 0}catch(w){if(typeof V=="undefined"||w.name!=="ErrnoError")throw w;return-w.oa}},r:function(a){try{return a=W(a),yb(a),0}catch(b){if(typeof V=="undefined"||b.name!=="ErrnoError")throw b;return-b.oa}},p:function(a,b){try{a=W(a);var c=P(a,{za:!0}).node;var d=pb(c.la.ta,63)(c);B[b>>2]=d.dev;B[b+4>>2]=d.mode;B[b+8>>2]=d.nlink;B[b+12>>2]=d.uid;B[b+16>>2]=d.gid;B[b+20>>2]=d.rdev;C[b+24>>
3]=BigInt(d.size);A[b+32>>2]=4096;A[b+36>>2]=d.blocks;var e=d.atime.getTime(),g=d.mtime.getTime(),h=d.ctime.getTime();C[b+40>>3]=BigInt(Math.floor(e/1E3));B[b+48>>2]=e%1E3*1E3*1E3;C[b+56>>3]=BigInt(Math.floor(g/1E3));B[b+64>>2]=g%1E3*1E3*1E3;C[b+72>>3]=BigInt(Math.floor(h/1E3));B[b+80>>2]=h%1E3*1E3*1E3;C[b+88>>3]=BigInt(d.ino);return 0}catch(m){if(typeof V=="undefined"||m.name!=="ErrnoError")throw m;return-m.oa}},s:function(a,b,c){try{b=W(b);b=X(a,b);if(c)if(c===512)yb(b);else return-28;else zb(b);
return 0}catch(d){if(typeof V=="undefined"||d.name!=="ErrnoError")throw d;return-d.oa}},i:()=>D(""),g:function(a,b,c){if(!(a>=0&&a<=3))return 28;C[c>>3]=BigInt(Math.round((a===0?Date.now():performance.now())*1E3*1E3));return 0},w:()=>Date.now(),o:a=>{var b=z.length;a>>>=0;if(a>2147483648)return!1;for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,Math.ceil(Math.max(a,d)/65536)*65536)-na.buffer.byteLength+65535)/65536|0;try{na.grow(d);ma();var e=1;break a}catch(g){}e=
void 0}if(e)return!0}return!1},e:()=>{D("Please compile your program with async support in order to use asynchronous operations like emscripten_sleep")},u:(a,b)=>{var c=0,d=0,e;for(e of Ob()){var g=b+c;B[a+d>>2]=g;c+=La(e,z,g,Infinity)+1;d+=4}return 0},v:(a,b)=>{var c=Ob();B[a>>2]=c.length;a=0;for(var d of c)a+=Ka(d)+1;B[b>>2]=a;return 0},f:a=>{Pb(a)},a:function(a){try{var b=S(a);Cb(b);return 0}catch(c){if(typeof V=="undefined"||c.name!=="ErrnoError")throw c;return c.oa}},j:function(a,b,c,d){try{a:{var e=
S(a);a=b;for(var g,h=b=0;h<c;h++){var m=B[a>>2],q=B[a+4>>2];a+=8;try{var f=e,l=m,n=q,r=g,t=p;if(n<0||r<0)throw new I(28);if(f.fd===null)throw new I(8);if((f.flags&2097155)===1)throw new I(8);if(K(f.node.mode))throw new I(31);if(!f.ma.read)throw new I(28);var u=typeof r!="undefined";if(!u)r=f.position;else if(!f.seekable)throw new I(70);var x=f.ma.read(f,t,l,n,r);u||(f.position+=x);var w=x}catch(F){if(b>0&&F instanceof I&&(F.oa==6||F.oa==6))break;throw F;}if(w<0){var y=-1;break a}b+=w;if(w<q)break;
typeof g!="undefined"&&(g+=w)}y=b}B[d>>2]=y;return 0}catch(F){if(typeof V=="undefined"||F.name!=="ErrnoError")throw F;return F.oa}},t:function(a,b,c,d){b=b<-9007199254740992||b>9007199254740992?NaN:Number(b);try{if(isNaN(b))return 22;var e=S(a);Db(e,b,c);C[d>>3]=BigInt(e.position);e.xa&&!b&&c===0&&(e.xa=null);return 0}catch(g){if(typeof V=="undefined"||g.name!=="ErrnoError")throw g;return g.oa}},b:function(a,b,c,d){try{var e=S(a);a=b;if(c==1)var g=Eb(e,p,B[a>>2],B[a+4>>2]);else{for(var h=b=0,m=a;h<
c;h++,m+=8)b+=B[m+4>>2];var q=new Uint8Array(b);for(h=m=0;h<c;h++,a+=8){var f=B[a>>2],l=B[a+4>>2];q.set(z.subarray(f,f+l),m);m+=l}g=Eb(e,q,0,b)}B[d>>2]=g;return 0}catch(n){if(typeof V=="undefined"||n.name!=="ErrnoError")throw n;return n.oa}},l:(a,b)=>Da(z.subarray(a,a+b))};function Wb(){var a=Ub;try{var b=a(0,0);Pb(b)}catch(c){c instanceof ya||c=="unwind"||ea(1,c)}}var Xb;
Xb=await (async function(){function a(d){d=Xb=d.exports;Module._d1_init=d.z;Module._d1_last_error=d.A;Module._d1_table_counts=d.B;Module._d1_save_open=d.C;Module._d1_save_close=d.D;Module._d1_hero_decode=d.E;Module._d1_hero_encode=d.F;Module._d1_save_export_len=d.G;Module._d1_save_export=d.H;Module._d1_hero_json=d.I;Module._d1_hero_set_name=d.J;Module._d1_hero_set_experience=d.K;Module._d1_hero_set_level=d.L;Module._d1_hero_set_stat_pts=d.M;Module._d1_hero_set_base_str=d.N;Module._d1_hero_set_base_mag=
d.O;Module._d1_hero_set_base_dex=d.P;Module._d1_hero_set_base_vit=d.Q;Module._d1_hero_set_hp_base=d.R;Module._d1_hero_set_max_hp_base=d.S;Module._d1_hero_set_mana_base=d.T;Module._d1_hero_set_max_mana_base=d.U;Module._d1_hero_set_plr_level=d.V;Module._d1_item_pack_size=d.W;Module._d1_item_json=d.X;Module._d1_hero_items_json=d.Y;Module._d1_preview_json=d.Z;Module._d1_hero_set_gold=d._;Module._d1_place_item_auto=d.$;Module._d1_equip_item=d.aa;Module._d1_remove_item=d.ba;Module._d1_discard_item=d.ca;
Module._d1_hero_stats_effective_json=d.da;Module._d1_legitimacy_json=d.ea;Ub=Module._main=d.fa;Module._free=d.ga;Module._malloc=d.ha;Sb=d.ia;Qb=d.ja;Rb=d.ka;na=d.x;ma();return Xb}var b={a:Vb},c=Module.instantiateWasm;if(c)return new Promise(d=>{c(b,e=>d(a(e)))});ua??=Module.locateFile?Module.locateFile("d1_core.wasm",fa):fa+"d1_core.wasm";return function(d){return a(d.instance)}(await xa(b))}());
await (async function(){qa();M&&await Za();var a=Module.setStatus;a&&(a("Running..."),await new Promise(b=>setTimeout(b,1)),setTimeout(a,1,""));la||(Module.noFSInit||hb||Fb(),Xb.y(),ib=!1,Module.onRuntimeInitialized?.(),Module.noInitialRun||Wb(),sa())}());
;return Module}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=createD1Core;module.exports.default=createD1Core}else if(typeof define==="function"&&define["amd"])define([],()=>createD1Core);
